language: node_js
node_js:
  - "stable"
  - "lts/*"
addons:
  rethinkdb: '2.3'
after_prepare:
  - "sudo service rethinkdb restart"
before_script:
  - "npm run lint"
  - "sudo service rethinkdb status"
