language: node_js
node_js:
  - "0.11"
before_install:
  - "git clone --depth 1 -b v1.13.x https://github.com/rethinkdb/rethinkdb.git"
  - "cd rethinkdb"
  - "./configure --allow-fetch"
  - "make -j 2"
  - "rethinkdb&"
