// Generated by CoffeeScript 1.7.0
(function() {
  'use strict';
  var Pool, debug, r;

  Pool = require('generic-pool').Pool;

  r = require('rethinkdb');

  debug = require('debug')('rethinkdb:pool');

  module.exports = function(options, max, min, idleTimeoutMillis) {
    return Pool({
      name: 'rethinkdb',
      create: function(done) {
        return r.connect(options, done);
      },
      destroy: function(connection) {
        return connection.close();
      },
      log: debug,
      max: max || 10,
      min: min || 2,
      idleTimeoutMillis: idleTimeoutMillis || 30000
    });
  };

}).call(this);
